### ISSUE TITLE
你这个qqwry.data库是自动还是手动更新到github的？

### ISSUE THREAD

**Issue by zjcnew** [zhaoyongtao/qqwry#1]
qqwry.data数据库是自动还是手动更新到github的？

**Comment by zhaoyongtao** [comment]
额...手动，首先是在Windows上升级到官方最新版，GitHub配置好公钥之后部署就很容易了。把add、commit、push 写成脚本就好了。方法很low。。。

**Comment by zjcnew** [comment]
Windows上更新库，目前好像只能手工，效率很低。。。
